//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Babylon.Services.References.MessageServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Metro.Services.Babylon/", ConfigurationName="MessageServiceReference.MessageService")]
    public interface MessageService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Metro.Services.Babylon/MessageService/CreateMessageRequest", ReplyAction="http://Metro.Services.Babylon/MessageService/CreateMessageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Babylon.Services.References.MessageServiceReference.CreateMessageResponse CreateMessage(Babylon.Services.References.MessageServiceReference.CreateMessageRequest request);
        
        // CODEGEN: Parameter 'message' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://Metro.Services.Babylon/MessageService/ModifyMessage")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void ModifyMessage(Babylon.Services.References.MessageServiceReference.ModifyMessage request);
        
        // CODEGEN: Parameter 'id' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://Metro.Services.Babylon/MessageService/DeleteMessage")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DeleteMessage(Babylon.Services.References.MessageServiceReference.DeleteMessage request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Metro.Services.Babylon/MessageService/GetSentMessagesRequest", ReplyAction="http://Metro.Services.Babylon/MessageService/GetSentMessagesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Babylon.Services.References.MessageServiceReference.GetSentMessagesResponse GetSentMessages(Babylon.Services.References.MessageServiceReference.GetSentMessagesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Metro.Services.Babylon/MessageService/GetReceivedMessagesRequest", ReplyAction="http://Metro.Services.Babylon/MessageService/GetReceivedMessagesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Babylon.Services.References.MessageServiceReference.GetReceivedMessagesResponse GetReceivedMessages(Babylon.Services.References.MessageServiceReference.GetReceivedMessagesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Metro.Services.Babylon/MessageService/SearchMessagesRequest", ReplyAction="http://Metro.Services.Babylon/MessageService/SearchMessagesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Babylon.Services.References.MessageServiceReference.SearchMessagesResponse SearchMessages(Babylon.Services.References.MessageServiceReference.SearchMessagesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Metro.Services.Babylon/MessageService/GetMessageRequest", ReplyAction="http://Metro.Services.Babylon/MessageService/GetMessageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Babylon.Services.References.MessageServiceReference.GetMessageResponse GetMessage(Babylon.Services.References.MessageServiceReference.GetMessageRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Metro.Services.Babylon/MessageService/SendMessageRequest", ReplyAction="http://Metro.Services.Babylon/MessageService/SendMessageResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Babylon.Services.References.MessageServiceReference.SendMessageResponse SendMessage(Babylon.Services.References.MessageServiceReference.SendMessageRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Metro.Services.Babylon/")]
    public partial class message : object, System.ComponentModel.INotifyPropertyChanged {
        
        private attachment[] attachmentsField;
        
        private string bodyField;
        
        private string idField;
        
        private string[] recipientsField;
        
        private string senderField;
        
        private System.DateTime sentOnField;
        
        private bool sentOnFieldSpecified;
        
        private string subjectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attachments", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public attachment[] attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
                this.RaisePropertyChanged("attachments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("body");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("recipients", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string[] recipients {
            get {
                return this.recipientsField;
            }
            set {
                this.recipientsField = value;
                this.RaisePropertyChanged("recipients");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime sentOn {
            get {
                return this.sentOnField;
            }
            set {
                this.sentOnField = value;
                this.RaisePropertyChanged("sentOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sentOnSpecified {
            get {
                return this.sentOnFieldSpecified;
            }
            set {
                this.sentOnFieldSpecified = value;
                this.RaisePropertyChanged("sentOnSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("subject");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Metro.Services.Babylon/")]
    public partial class attachment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private byte[] contentField;
        
        private string linkField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
                this.RaisePropertyChanged("link");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Metro.Services.Babylon/")]
    public partial class messageFilter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime sentAfterField;
        
        private bool sentAfterFieldSpecified;
        
        private System.DateTime sentBeforeField;
        
        private bool sentBeforeFieldSpecified;
        
        private string sentByField;
        
        private string subjectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime sentAfter {
            get {
                return this.sentAfterField;
            }
            set {
                this.sentAfterField = value;
                this.RaisePropertyChanged("sentAfter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sentAfterSpecified {
            get {
                return this.sentAfterFieldSpecified;
            }
            set {
                this.sentAfterFieldSpecified = value;
                this.RaisePropertyChanged("sentAfterSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime sentBefore {
            get {
                return this.sentBeforeField;
            }
            set {
                this.sentBeforeField = value;
                this.RaisePropertyChanged("sentBefore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sentBeforeSpecified {
            get {
                return this.sentBeforeFieldSpecified;
            }
            set {
                this.sentBeforeFieldSpecified = value;
                this.RaisePropertyChanged("sentBeforeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string sentBy {
            get {
                return this.sentByField;
            }
            set {
                this.sentByField = value;
                this.RaisePropertyChanged("sentBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("subject");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMessage", WrapperNamespace="http://Metro.Services.Babylon/", IsWrapped=true)]
    public partial class CreateMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Metro.Services.Babylon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sender;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Metro.Services.Babylon/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("recipients", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] recipients;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Metro.Services.Babylon/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string subject;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Metro.Services.Babylon/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string body;
        
        public CreateMessageRequest() {
        }
        
        public CreateMessageRequest(string sender, string[] recipients, string subject, string body) {
            this.sender = sender;
            this.recipients = recipients;
            this.subject = subject;
            this.body = body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateMessageResponse", WrapperNamespace="http://Metro.Services.Babylon/", IsWrapped=true)]
    public partial class CreateMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Metro.Services.Babylon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Babylon.Services.References.MessageServiceReference.message @return;
        
        public CreateMessageResponse() {
        }
        
        public CreateMessageResponse(Babylon.Services.References.MessageServiceReference.message @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ModifyMessage", WrapperNamespace="http://Metro.Services.Babylon/", IsWrapped=true)]
    public partial class ModifyMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Metro.Services.Babylon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Babylon.Services.References.MessageServiceReference.message message;
        
        public ModifyMessage() {
        }
        
        public ModifyMessage(Babylon.Services.References.MessageServiceReference.message message) {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteMessage", WrapperNamespace="http://Metro.Services.Babylon/", IsWrapped=true)]
    public partial class DeleteMessage {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Metro.Services.Babylon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id;
        
        public DeleteMessage() {
        }
        
        public DeleteMessage(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSentMessages", WrapperNamespace="http://Metro.Services.Babylon/", IsWrapped=true)]
    public partial class GetSentMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Metro.Services.Babylon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sender;
        
        public GetSentMessagesRequest() {
        }
        
        public GetSentMessagesRequest(string sender) {
            this.sender = sender;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSentMessagesResponse", WrapperNamespace="http://Metro.Services.Babylon/", IsWrapped=true)]
    public partial class GetSentMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Metro.Services.Babylon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public message[] @return;
        
        public GetSentMessagesResponse() {
        }
        
        public GetSentMessagesResponse(message[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReceivedMessages", WrapperNamespace="http://Metro.Services.Babylon/", IsWrapped=true)]
    public partial class GetReceivedMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Metro.Services.Babylon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string recipient;
        
        public GetReceivedMessagesRequest() {
        }
        
        public GetReceivedMessagesRequest(string recipient) {
            this.recipient = recipient;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetReceivedMessagesResponse", WrapperNamespace="http://Metro.Services.Babylon/", IsWrapped=true)]
    public partial class GetReceivedMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Metro.Services.Babylon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public message[] @return;
        
        public GetReceivedMessagesResponse() {
        }
        
        public GetReceivedMessagesResponse(message[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchMessages", WrapperNamespace="http://Metro.Services.Babylon/", IsWrapped=true)]
    public partial class SearchMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Metro.Services.Babylon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Babylon.Services.References.MessageServiceReference.messageFilter filter;
        
        public SearchMessagesRequest() {
        }
        
        public SearchMessagesRequest(Babylon.Services.References.MessageServiceReference.messageFilter filter) {
            this.filter = filter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchMessagesResponse", WrapperNamespace="http://Metro.Services.Babylon/", IsWrapped=true)]
    public partial class SearchMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Metro.Services.Babylon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public message[] @return;
        
        public SearchMessagesResponse() {
        }
        
        public SearchMessagesResponse(message[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessage", WrapperNamespace="http://Metro.Services.Babylon/", IsWrapped=true)]
    public partial class GetMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Metro.Services.Babylon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id;
        
        public GetMessageRequest() {
        }
        
        public GetMessageRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageResponse", WrapperNamespace="http://Metro.Services.Babylon/", IsWrapped=true)]
    public partial class GetMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Metro.Services.Babylon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Babylon.Services.References.MessageServiceReference.message @return;
        
        public GetMessageResponse() {
        }
        
        public GetMessageResponse(Babylon.Services.References.MessageServiceReference.message @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessage", WrapperNamespace="http://Metro.Services.Babylon/", IsWrapped=true)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Metro.Services.Babylon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Babylon.Services.References.MessageServiceReference.message message;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(Babylon.Services.References.MessageServiceReference.message message) {
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageResponse", WrapperNamespace="http://Metro.Services.Babylon/", IsWrapped=true)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Metro.Services.Babylon/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MessageServiceChannel : Babylon.Services.References.MessageServiceReference.MessageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageServiceClient : System.ServiceModel.ClientBase<Babylon.Services.References.MessageServiceReference.MessageService>, Babylon.Services.References.MessageServiceReference.MessageService {
        
        public MessageServiceClient() {
        }
        
        public MessageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Babylon.Services.References.MessageServiceReference.CreateMessageResponse Babylon.Services.References.MessageServiceReference.MessageService.CreateMessage(Babylon.Services.References.MessageServiceReference.CreateMessageRequest request) {
            return base.Channel.CreateMessage(request);
        }
        
        public Babylon.Services.References.MessageServiceReference.message CreateMessage(string sender, string[] recipients, string subject, string body) {
            Babylon.Services.References.MessageServiceReference.CreateMessageRequest inValue = new Babylon.Services.References.MessageServiceReference.CreateMessageRequest();
            inValue.sender = sender;
            inValue.recipients = recipients;
            inValue.subject = subject;
            inValue.body = body;
            Babylon.Services.References.MessageServiceReference.CreateMessageResponse retVal = ((Babylon.Services.References.MessageServiceReference.MessageService)(this)).CreateMessage(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Babylon.Services.References.MessageServiceReference.MessageService.ModifyMessage(Babylon.Services.References.MessageServiceReference.ModifyMessage request) {
            base.Channel.ModifyMessage(request);
        }
        
        public void ModifyMessage(Babylon.Services.References.MessageServiceReference.message message) {
            Babylon.Services.References.MessageServiceReference.ModifyMessage inValue = new Babylon.Services.References.MessageServiceReference.ModifyMessage();
            inValue.message = message;
            ((Babylon.Services.References.MessageServiceReference.MessageService)(this)).ModifyMessage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Babylon.Services.References.MessageServiceReference.MessageService.DeleteMessage(Babylon.Services.References.MessageServiceReference.DeleteMessage request) {
            base.Channel.DeleteMessage(request);
        }
        
        public void DeleteMessage(string id) {
            Babylon.Services.References.MessageServiceReference.DeleteMessage inValue = new Babylon.Services.References.MessageServiceReference.DeleteMessage();
            inValue.id = id;
            ((Babylon.Services.References.MessageServiceReference.MessageService)(this)).DeleteMessage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Babylon.Services.References.MessageServiceReference.GetSentMessagesResponse Babylon.Services.References.MessageServiceReference.MessageService.GetSentMessages(Babylon.Services.References.MessageServiceReference.GetSentMessagesRequest request) {
            return base.Channel.GetSentMessages(request);
        }
        
        public message[] GetSentMessages(string sender) {
            Babylon.Services.References.MessageServiceReference.GetSentMessagesRequest inValue = new Babylon.Services.References.MessageServiceReference.GetSentMessagesRequest();
            inValue.sender = sender;
            Babylon.Services.References.MessageServiceReference.GetSentMessagesResponse retVal = ((Babylon.Services.References.MessageServiceReference.MessageService)(this)).GetSentMessages(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Babylon.Services.References.MessageServiceReference.GetReceivedMessagesResponse Babylon.Services.References.MessageServiceReference.MessageService.GetReceivedMessages(Babylon.Services.References.MessageServiceReference.GetReceivedMessagesRequest request) {
            return base.Channel.GetReceivedMessages(request);
        }
        
        public message[] GetReceivedMessages(string recipient) {
            Babylon.Services.References.MessageServiceReference.GetReceivedMessagesRequest inValue = new Babylon.Services.References.MessageServiceReference.GetReceivedMessagesRequest();
            inValue.recipient = recipient;
            Babylon.Services.References.MessageServiceReference.GetReceivedMessagesResponse retVal = ((Babylon.Services.References.MessageServiceReference.MessageService)(this)).GetReceivedMessages(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Babylon.Services.References.MessageServiceReference.SearchMessagesResponse Babylon.Services.References.MessageServiceReference.MessageService.SearchMessages(Babylon.Services.References.MessageServiceReference.SearchMessagesRequest request) {
            return base.Channel.SearchMessages(request);
        }
        
        public message[] SearchMessages(Babylon.Services.References.MessageServiceReference.messageFilter filter) {
            Babylon.Services.References.MessageServiceReference.SearchMessagesRequest inValue = new Babylon.Services.References.MessageServiceReference.SearchMessagesRequest();
            inValue.filter = filter;
            Babylon.Services.References.MessageServiceReference.SearchMessagesResponse retVal = ((Babylon.Services.References.MessageServiceReference.MessageService)(this)).SearchMessages(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Babylon.Services.References.MessageServiceReference.GetMessageResponse Babylon.Services.References.MessageServiceReference.MessageService.GetMessage(Babylon.Services.References.MessageServiceReference.GetMessageRequest request) {
            return base.Channel.GetMessage(request);
        }
        
        public Babylon.Services.References.MessageServiceReference.message GetMessage(string id) {
            Babylon.Services.References.MessageServiceReference.GetMessageRequest inValue = new Babylon.Services.References.MessageServiceReference.GetMessageRequest();
            inValue.id = id;
            Babylon.Services.References.MessageServiceReference.GetMessageResponse retVal = ((Babylon.Services.References.MessageServiceReference.MessageService)(this)).GetMessage(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Babylon.Services.References.MessageServiceReference.SendMessageResponse Babylon.Services.References.MessageServiceReference.MessageService.SendMessage(Babylon.Services.References.MessageServiceReference.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public string SendMessage(Babylon.Services.References.MessageServiceReference.message message) {
            Babylon.Services.References.MessageServiceReference.SendMessageRequest inValue = new Babylon.Services.References.MessageServiceReference.SendMessageRequest();
            inValue.message = message;
            Babylon.Services.References.MessageServiceReference.SendMessageResponse retVal = ((Babylon.Services.References.MessageServiceReference.MessageService)(this)).SendMessage(inValue);
            return retVal.@return;
        }
    }
}
