//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Babylon.Services.Proxies.ProfileServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfguid", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", ItemName="guid")]
    [System.SerializableAttribute()]
    public class ArrayOfguid : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profile", Namespace="http://schemas.datacontract.org/2004/07/Babel.Services.Domain")]
    [System.SerializableAttribute()]
    public partial class Profile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Babylon.Services.Proxies.ProfileServiceReference.Address AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<Babylon.Services.Proxies.ProfileServiceReference.Gender> GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PictureUploadedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Babylon.Services.Proxies.ProfileServiceReference.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Babylon.Services.Proxies.ProfileServiceReference.Gender> Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PictureUploadedOn {
            get {
                return this.PictureUploadedOnField;
            }
            set {
                if ((this.PictureUploadedOnField.Equals(value) != true)) {
                    this.PictureUploadedOnField = value;
                    this.RaisePropertyChanged("PictureUploadedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedOn {
            get {
                return this.UpdatedOnField;
            }
            set {
                if ((this.UpdatedOnField.Equals(value) != true)) {
                    this.UpdatedOnField = value;
                    this.RaisePropertyChanged("UpdatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/Babel.Services.Domain")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gender", Namespace="http://schemas.datacontract.org/2004/07/Babel.Services.Common")]
    public enum Gender : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Metro.Services.Babylon/", ConfigurationName="ProfileServiceReference.ProfileService")]
    public interface ProfileService {
        
        // CODEGEN: Generating message contract since element name id from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Metro.Services.Babylon/ProfileService/AddContactRequest", ReplyAction="http://Metro.Services.Babylon/ProfileService/AddContactResponse")]
        Babylon.Services.Proxies.ProfileServiceReference.AddContactResponse AddContact(Babylon.Services.Proxies.ProfileServiceReference.AddContactRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Metro.Services.Babylon/ProfileService/AddContactsRequest", ReplyAction="http://Metro.Services.Babylon/ProfileService/AddContactsResponse")]
        Babylon.Services.Proxies.ProfileServiceReference.AddContactsResponse AddContacts(Babylon.Services.Proxies.ProfileServiceReference.AddContactsRequest request);
        
        // CODEGEN: Generating message contract since element name profile from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Metro.Services.Babylon/ProfileService/AddProfileRequest", ReplyAction="http://Metro.Services.Babylon/ProfileService/AddProfileResponse")]
        Babylon.Services.Proxies.ProfileServiceReference.AddProfileResponse AddProfile(Babylon.Services.Proxies.ProfileServiceReference.AddProfileRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Metro.Services.Babylon/ProfileService/CreateProfileRequest", ReplyAction="http://Metro.Services.Babylon/ProfileService/CreateProfileResponse")]
        Babylon.Services.Proxies.ProfileServiceReference.CreateProfileResponse CreateProfile(Babylon.Services.Proxies.ProfileServiceReference.CreateProfileRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Metro.Services.Babylon/ProfileService/DeleteProfileRequest", ReplyAction="http://Metro.Services.Babylon/ProfileService/DeleteProfileResponse")]
        Babylon.Services.Proxies.ProfileServiceReference.DeleteProfileResponse DeleteProfile(Babylon.Services.Proxies.ProfileServiceReference.DeleteProfileRequest request);
        
        // CODEGEN: Generating message contract since element name return from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Metro.Services.Babylon/ProfileService/GetAllProfilesRequest", ReplyAction="http://Metro.Services.Babylon/ProfileService/GetAllProfilesResponse")]
        Babylon.Services.Proxies.ProfileServiceReference.GetAllProfilesResponse GetAllProfiles(Babylon.Services.Proxies.ProfileServiceReference.GetAllProfilesRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Metro.Services.Babylon/ProfileService/GetContactsRequest", ReplyAction="http://Metro.Services.Babylon/ProfileService/GetContactsResponse")]
        Babylon.Services.Proxies.ProfileServiceReference.GetContactsResponse GetContacts(Babylon.Services.Proxies.ProfileServiceReference.GetContactsRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Metro.Services.Babylon/ProfileService/GetProfileByCredentialsRequest", ReplyAction="http://Metro.Services.Babylon/ProfileService/GetProfileByCredentialsResponse")]
        Babylon.Services.Proxies.ProfileServiceReference.GetProfileByCredentialsResponse GetProfileByCredentials(Babylon.Services.Proxies.ProfileServiceReference.GetProfileByCredentialsRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Metro.Services.Babylon/ProfileService/GetProfileByIDRequest", ReplyAction="http://Metro.Services.Babylon/ProfileService/GetProfileByIDResponse")]
        Babylon.Services.Proxies.ProfileServiceReference.GetProfileByIDResponse GetProfileByID(Babylon.Services.Proxies.ProfileServiceReference.GetProfileByIDRequest request);
        
        // CODEGEN: Generating message contract since element name profile from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Metro.Services.Babylon/ProfileService/ModifyProfileRequest", ReplyAction="http://Metro.Services.Babylon/ProfileService/ModifyProfileResponse")]
        Babylon.Services.Proxies.ProfileServiceReference.ModifyProfileResponse ModifyProfile(Babylon.Services.Proxies.ProfileServiceReference.ModifyProfileRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Metro.Services.Babylon/ProfileService/RemoveAllContactsRequest", ReplyAction="http://Metro.Services.Babylon/ProfileService/RemoveAllContactsResponse")]
        Babylon.Services.Proxies.ProfileServiceReference.RemoveAllContactsResponse RemoveAllContacts(Babylon.Services.Proxies.ProfileServiceReference.RemoveAllContactsRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://Metro.Services.Babylon/ProfileService/RemoveContactRequest", ReplyAction="http://Metro.Services.Babylon/ProfileService/RemoveContactResponse")]
        Babylon.Services.Proxies.ProfileServiceReference.RemoveContactResponse RemoveContact(Babylon.Services.Proxies.ProfileServiceReference.RemoveContactRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddContactRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddContact", Namespace="http://Metro.Services.Babylon/", Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.AddContactRequestBody Body;
        
        public AddContactRequest() {
        }
        
        public AddContactRequest(Babylon.Services.Proxies.ProfileServiceReference.AddContactRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class AddContactRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        public AddContactRequestBody() {
        }
        
        public AddContactRequestBody(string id, string name) {
            this.id = id;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddContactResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddContactResponse", Namespace="http://Metro.Services.Babylon/", Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.AddContactResponseBody Body;
        
        public AddContactResponse() {
        }
        
        public AddContactResponse(Babylon.Services.Proxies.ProfileServiceReference.AddContactResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddContactResponseBody {
        
        public AddContactResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddContactsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddContacts", Namespace="http://Metro.Services.Babylon/", Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.AddContactsRequestBody Body;
        
        public AddContactsRequest() {
        }
        
        public AddContactsRequest(Babylon.Services.Proxies.ProfileServiceReference.AddContactsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class AddContactsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Babylon.Services.Proxies.ProfileServiceReference.ArrayOfguid contactIDs;
        
        public AddContactsRequestBody() {
        }
        
        public AddContactsRequestBody(string id, Babylon.Services.Proxies.ProfileServiceReference.ArrayOfguid contactIDs) {
            this.id = id;
            this.contactIDs = contactIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddContactsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddContactsResponse", Namespace="http://Metro.Services.Babylon/", Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.AddContactsResponseBody Body;
        
        public AddContactsResponse() {
        }
        
        public AddContactsResponse(Babylon.Services.Proxies.ProfileServiceReference.AddContactsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddContactsResponseBody {
        
        public AddContactsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProfile", Namespace="http://Metro.Services.Babylon/", Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.AddProfileRequestBody Body;
        
        public AddProfileRequest() {
        }
        
        public AddProfileRequest(Babylon.Services.Proxies.ProfileServiceReference.AddProfileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class AddProfileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.Profile profile;
        
        public AddProfileRequestBody() {
        }
        
        public AddProfileRequestBody(Babylon.Services.Proxies.ProfileServiceReference.Profile profile) {
            this.profile = profile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddProfileResponse", Namespace="http://Metro.Services.Babylon/", Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.AddProfileResponseBody Body;
        
        public AddProfileResponse() {
        }
        
        public AddProfileResponse(Babylon.Services.Proxies.ProfileServiceReference.AddProfileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class AddProfileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public AddProfileResponseBody() {
        }
        
        public AddProfileResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateProfile", Namespace="http://Metro.Services.Babylon/", Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.CreateProfileRequestBody Body;
        
        public CreateProfileRequest() {
        }
        
        public CreateProfileRequest(Babylon.Services.Proxies.ProfileServiceReference.CreateProfileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class CreateProfileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string surname;
        
        public CreateProfileRequestBody() {
        }
        
        public CreateProfileRequestBody(string username, string password, string email, string name, string surname) {
            this.username = username;
            this.password = password;
            this.email = email;
            this.name = name;
            this.surname = surname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateProfileResponse", Namespace="http://Metro.Services.Babylon/", Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.CreateProfileResponseBody Body;
        
        public CreateProfileResponse() {
        }
        
        public CreateProfileResponse(Babylon.Services.Proxies.ProfileServiceReference.CreateProfileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class CreateProfileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public CreateProfileResponseBody() {
        }
        
        public CreateProfileResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteProfile", Namespace="http://Metro.Services.Babylon/", Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.DeleteProfileRequestBody Body;
        
        public DeleteProfileRequest() {
        }
        
        public DeleteProfileRequest(Babylon.Services.Proxies.ProfileServiceReference.DeleteProfileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class DeleteProfileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public DeleteProfileRequestBody() {
        }
        
        public DeleteProfileRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteProfileResponse", Namespace="http://Metro.Services.Babylon/", Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.DeleteProfileResponseBody Body;
        
        public DeleteProfileResponse() {
        }
        
        public DeleteProfileResponse(Babylon.Services.Proxies.ProfileServiceReference.DeleteProfileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteProfileResponseBody {
        
        public DeleteProfileResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProfilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProfiles", Namespace="http://Metro.Services.Babylon/", Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.GetAllProfilesRequestBody Body;
        
        public GetAllProfilesRequest() {
        }
        
        public GetAllProfilesRequest(Babylon.Services.Proxies.ProfileServiceReference.GetAllProfilesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllProfilesRequestBody {
        
        public GetAllProfilesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProfilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProfilesResponse", Namespace="http://Metro.Services.Babylon/", Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.GetAllProfilesResponseBody Body;
        
        public GetAllProfilesResponse() {
        }
        
        public GetAllProfilesResponse(Babylon.Services.Proxies.ProfileServiceReference.GetAllProfilesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetAllProfilesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Babylon.Services.Proxies.ProfileServiceReference.Profile> @return;
        
        public GetAllProfilesResponseBody() {
        }
        
        public GetAllProfilesResponseBody(System.Collections.Generic.List<Babylon.Services.Proxies.ProfileServiceReference.Profile> @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContactsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContacts", Namespace="http://Metro.Services.Babylon/", Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.GetContactsRequestBody Body;
        
        public GetContactsRequest() {
        }
        
        public GetContactsRequest(Babylon.Services.Proxies.ProfileServiceReference.GetContactsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetContactsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public GetContactsRequestBody() {
        }
        
        public GetContactsRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContactsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContactsResponse", Namespace="http://Metro.Services.Babylon/", Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.GetContactsResponseBody Body;
        
        public GetContactsResponse() {
        }
        
        public GetContactsResponse(Babylon.Services.Proxies.ProfileServiceReference.GetContactsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetContactsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Babylon.Services.Proxies.ProfileServiceReference.Profile> @return;
        
        public GetContactsResponseBody() {
        }
        
        public GetContactsResponseBody(System.Collections.Generic.List<Babylon.Services.Proxies.ProfileServiceReference.Profile> @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProfileByCredentialsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProfileByCredentials", Namespace="http://Metro.Services.Babylon/", Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.GetProfileByCredentialsRequestBody Body;
        
        public GetProfileByCredentialsRequest() {
        }
        
        public GetProfileByCredentialsRequest(Babylon.Services.Proxies.ProfileServiceReference.GetProfileByCredentialsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetProfileByCredentialsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetProfileByCredentialsRequestBody() {
        }
        
        public GetProfileByCredentialsRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProfileByCredentialsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProfileByCredentialsResponse", Namespace="http://Metro.Services.Babylon/", Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.GetProfileByCredentialsResponseBody Body;
        
        public GetProfileByCredentialsResponse() {
        }
        
        public GetProfileByCredentialsResponse(Babylon.Services.Proxies.ProfileServiceReference.GetProfileByCredentialsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetProfileByCredentialsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.Profile @return;
        
        public GetProfileByCredentialsResponseBody() {
        }
        
        public GetProfileByCredentialsResponseBody(Babylon.Services.Proxies.ProfileServiceReference.Profile @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProfileByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProfileByID", Namespace="http://Metro.Services.Babylon/", Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.GetProfileByIDRequestBody Body;
        
        public GetProfileByIDRequest() {
        }
        
        public GetProfileByIDRequest(Babylon.Services.Proxies.ProfileServiceReference.GetProfileByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetProfileByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public GetProfileByIDRequestBody() {
        }
        
        public GetProfileByIDRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProfileByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProfileByIDResponse", Namespace="http://Metro.Services.Babylon/", Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.GetProfileByIDResponseBody Body;
        
        public GetProfileByIDResponse() {
        }
        
        public GetProfileByIDResponse(Babylon.Services.Proxies.ProfileServiceReference.GetProfileByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetProfileByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.Profile @return;
        
        public GetProfileByIDResponseBody() {
        }
        
        public GetProfileByIDResponseBody(Babylon.Services.Proxies.ProfileServiceReference.Profile @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyProfileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyProfile", Namespace="http://Metro.Services.Babylon/", Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.ModifyProfileRequestBody Body;
        
        public ModifyProfileRequest() {
        }
        
        public ModifyProfileRequest(Babylon.Services.Proxies.ProfileServiceReference.ModifyProfileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class ModifyProfileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.Profile profile;
        
        public ModifyProfileRequestBody() {
        }
        
        public ModifyProfileRequestBody(Babylon.Services.Proxies.ProfileServiceReference.Profile profile) {
            this.profile = profile;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyProfileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyProfileResponse", Namespace="http://Metro.Services.Babylon/", Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.ModifyProfileResponseBody Body;
        
        public ModifyProfileResponse() {
        }
        
        public ModifyProfileResponse(Babylon.Services.Proxies.ProfileServiceReference.ModifyProfileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ModifyProfileResponseBody {
        
        public ModifyProfileResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveAllContactsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveAllContacts", Namespace="http://Metro.Services.Babylon/", Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.RemoveAllContactsRequestBody Body;
        
        public RemoveAllContactsRequest() {
        }
        
        public RemoveAllContactsRequest(Babylon.Services.Proxies.ProfileServiceReference.RemoveAllContactsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RemoveAllContactsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public RemoveAllContactsRequestBody() {
        }
        
        public RemoveAllContactsRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveAllContactsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveAllContactsResponse", Namespace="http://Metro.Services.Babylon/", Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.RemoveAllContactsResponseBody Body;
        
        public RemoveAllContactsResponse() {
        }
        
        public RemoveAllContactsResponse(Babylon.Services.Proxies.ProfileServiceReference.RemoveAllContactsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RemoveAllContactsResponseBody {
        
        public RemoveAllContactsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveContactRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveContact", Namespace="http://Metro.Services.Babylon/", Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.RemoveContactRequestBody Body;
        
        public RemoveContactRequest() {
        }
        
        public RemoveContactRequest(Babylon.Services.Proxies.ProfileServiceReference.RemoveContactRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RemoveContactRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contactID;
        
        public RemoveContactRequestBody() {
        }
        
        public RemoveContactRequestBody(string id, string contactID) {
            this.id = id;
            this.contactID = contactID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveContactResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveContactResponse", Namespace="http://Metro.Services.Babylon/", Order=0)]
        public Babylon.Services.Proxies.ProfileServiceReference.RemoveContactResponseBody Body;
        
        public RemoveContactResponse() {
        }
        
        public RemoveContactResponse(Babylon.Services.Proxies.ProfileServiceReference.RemoveContactResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RemoveContactResponseBody {
        
        public RemoveContactResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProfileServiceChannel : Babylon.Services.Proxies.ProfileServiceReference.ProfileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfileServiceClient : System.ServiceModel.ClientBase<Babylon.Services.Proxies.ProfileServiceReference.ProfileService>, Babylon.Services.Proxies.ProfileServiceReference.ProfileService {
        
        public ProfileServiceClient() {
        }
        
        public ProfileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Babylon.Services.Proxies.ProfileServiceReference.AddContactResponse Babylon.Services.Proxies.ProfileServiceReference.ProfileService.AddContact(Babylon.Services.Proxies.ProfileServiceReference.AddContactRequest request) {
            return base.Channel.AddContact(request);
        }
        
        public void AddContact(string id, string name) {
            Babylon.Services.Proxies.ProfileServiceReference.AddContactRequest inValue = new Babylon.Services.Proxies.ProfileServiceReference.AddContactRequest();
            inValue.Body = new Babylon.Services.Proxies.ProfileServiceReference.AddContactRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            Babylon.Services.Proxies.ProfileServiceReference.AddContactResponse retVal = ((Babylon.Services.Proxies.ProfileServiceReference.ProfileService)(this)).AddContact(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Babylon.Services.Proxies.ProfileServiceReference.AddContactsResponse Babylon.Services.Proxies.ProfileServiceReference.ProfileService.AddContacts(Babylon.Services.Proxies.ProfileServiceReference.AddContactsRequest request) {
            return base.Channel.AddContacts(request);
        }
        
        public void AddContacts(string id, Babylon.Services.Proxies.ProfileServiceReference.ArrayOfguid contactIDs) {
            Babylon.Services.Proxies.ProfileServiceReference.AddContactsRequest inValue = new Babylon.Services.Proxies.ProfileServiceReference.AddContactsRequest();
            inValue.Body = new Babylon.Services.Proxies.ProfileServiceReference.AddContactsRequestBody();
            inValue.Body.id = id;
            inValue.Body.contactIDs = contactIDs;
            Babylon.Services.Proxies.ProfileServiceReference.AddContactsResponse retVal = ((Babylon.Services.Proxies.ProfileServiceReference.ProfileService)(this)).AddContacts(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Babylon.Services.Proxies.ProfileServiceReference.AddProfileResponse Babylon.Services.Proxies.ProfileServiceReference.ProfileService.AddProfile(Babylon.Services.Proxies.ProfileServiceReference.AddProfileRequest request) {
            return base.Channel.AddProfile(request);
        }
        
        public string AddProfile(Babylon.Services.Proxies.ProfileServiceReference.Profile profile) {
            Babylon.Services.Proxies.ProfileServiceReference.AddProfileRequest inValue = new Babylon.Services.Proxies.ProfileServiceReference.AddProfileRequest();
            inValue.Body = new Babylon.Services.Proxies.ProfileServiceReference.AddProfileRequestBody();
            inValue.Body.profile = profile;
            Babylon.Services.Proxies.ProfileServiceReference.AddProfileResponse retVal = ((Babylon.Services.Proxies.ProfileServiceReference.ProfileService)(this)).AddProfile(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Babylon.Services.Proxies.ProfileServiceReference.CreateProfileResponse Babylon.Services.Proxies.ProfileServiceReference.ProfileService.CreateProfile(Babylon.Services.Proxies.ProfileServiceReference.CreateProfileRequest request) {
            return base.Channel.CreateProfile(request);
        }
        
        public string CreateProfile(string username, string password, string email, string name, string surname) {
            Babylon.Services.Proxies.ProfileServiceReference.CreateProfileRequest inValue = new Babylon.Services.Proxies.ProfileServiceReference.CreateProfileRequest();
            inValue.Body = new Babylon.Services.Proxies.ProfileServiceReference.CreateProfileRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.name = name;
            inValue.Body.surname = surname;
            Babylon.Services.Proxies.ProfileServiceReference.CreateProfileResponse retVal = ((Babylon.Services.Proxies.ProfileServiceReference.ProfileService)(this)).CreateProfile(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Babylon.Services.Proxies.ProfileServiceReference.DeleteProfileResponse Babylon.Services.Proxies.ProfileServiceReference.ProfileService.DeleteProfile(Babylon.Services.Proxies.ProfileServiceReference.DeleteProfileRequest request) {
            return base.Channel.DeleteProfile(request);
        }
        
        public void DeleteProfile(string id) {
            Babylon.Services.Proxies.ProfileServiceReference.DeleteProfileRequest inValue = new Babylon.Services.Proxies.ProfileServiceReference.DeleteProfileRequest();
            inValue.Body = new Babylon.Services.Proxies.ProfileServiceReference.DeleteProfileRequestBody();
            inValue.Body.id = id;
            Babylon.Services.Proxies.ProfileServiceReference.DeleteProfileResponse retVal = ((Babylon.Services.Proxies.ProfileServiceReference.ProfileService)(this)).DeleteProfile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Babylon.Services.Proxies.ProfileServiceReference.GetAllProfilesResponse Babylon.Services.Proxies.ProfileServiceReference.ProfileService.GetAllProfiles(Babylon.Services.Proxies.ProfileServiceReference.GetAllProfilesRequest request) {
            return base.Channel.GetAllProfiles(request);
        }
        
        public System.Collections.Generic.List<Babylon.Services.Proxies.ProfileServiceReference.Profile> GetAllProfiles() {
            Babylon.Services.Proxies.ProfileServiceReference.GetAllProfilesRequest inValue = new Babylon.Services.Proxies.ProfileServiceReference.GetAllProfilesRequest();
            inValue.Body = new Babylon.Services.Proxies.ProfileServiceReference.GetAllProfilesRequestBody();
            Babylon.Services.Proxies.ProfileServiceReference.GetAllProfilesResponse retVal = ((Babylon.Services.Proxies.ProfileServiceReference.ProfileService)(this)).GetAllProfiles(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Babylon.Services.Proxies.ProfileServiceReference.GetContactsResponse Babylon.Services.Proxies.ProfileServiceReference.ProfileService.GetContacts(Babylon.Services.Proxies.ProfileServiceReference.GetContactsRequest request) {
            return base.Channel.GetContacts(request);
        }
        
        public System.Collections.Generic.List<Babylon.Services.Proxies.ProfileServiceReference.Profile> GetContacts(string id) {
            Babylon.Services.Proxies.ProfileServiceReference.GetContactsRequest inValue = new Babylon.Services.Proxies.ProfileServiceReference.GetContactsRequest();
            inValue.Body = new Babylon.Services.Proxies.ProfileServiceReference.GetContactsRequestBody();
            inValue.Body.id = id;
            Babylon.Services.Proxies.ProfileServiceReference.GetContactsResponse retVal = ((Babylon.Services.Proxies.ProfileServiceReference.ProfileService)(this)).GetContacts(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Babylon.Services.Proxies.ProfileServiceReference.GetProfileByCredentialsResponse Babylon.Services.Proxies.ProfileServiceReference.ProfileService.GetProfileByCredentials(Babylon.Services.Proxies.ProfileServiceReference.GetProfileByCredentialsRequest request) {
            return base.Channel.GetProfileByCredentials(request);
        }
        
        public Babylon.Services.Proxies.ProfileServiceReference.Profile GetProfileByCredentials(string username, string password) {
            Babylon.Services.Proxies.ProfileServiceReference.GetProfileByCredentialsRequest inValue = new Babylon.Services.Proxies.ProfileServiceReference.GetProfileByCredentialsRequest();
            inValue.Body = new Babylon.Services.Proxies.ProfileServiceReference.GetProfileByCredentialsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Babylon.Services.Proxies.ProfileServiceReference.GetProfileByCredentialsResponse retVal = ((Babylon.Services.Proxies.ProfileServiceReference.ProfileService)(this)).GetProfileByCredentials(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Babylon.Services.Proxies.ProfileServiceReference.GetProfileByIDResponse Babylon.Services.Proxies.ProfileServiceReference.ProfileService.GetProfileByID(Babylon.Services.Proxies.ProfileServiceReference.GetProfileByIDRequest request) {
            return base.Channel.GetProfileByID(request);
        }
        
        public Babylon.Services.Proxies.ProfileServiceReference.Profile GetProfileByID(string id) {
            Babylon.Services.Proxies.ProfileServiceReference.GetProfileByIDRequest inValue = new Babylon.Services.Proxies.ProfileServiceReference.GetProfileByIDRequest();
            inValue.Body = new Babylon.Services.Proxies.ProfileServiceReference.GetProfileByIDRequestBody();
            inValue.Body.id = id;
            Babylon.Services.Proxies.ProfileServiceReference.GetProfileByIDResponse retVal = ((Babylon.Services.Proxies.ProfileServiceReference.ProfileService)(this)).GetProfileByID(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Babylon.Services.Proxies.ProfileServiceReference.ModifyProfileResponse Babylon.Services.Proxies.ProfileServiceReference.ProfileService.ModifyProfile(Babylon.Services.Proxies.ProfileServiceReference.ModifyProfileRequest request) {
            return base.Channel.ModifyProfile(request);
        }
        
        public void ModifyProfile(Babylon.Services.Proxies.ProfileServiceReference.Profile profile) {
            Babylon.Services.Proxies.ProfileServiceReference.ModifyProfileRequest inValue = new Babylon.Services.Proxies.ProfileServiceReference.ModifyProfileRequest();
            inValue.Body = new Babylon.Services.Proxies.ProfileServiceReference.ModifyProfileRequestBody();
            inValue.Body.profile = profile;
            Babylon.Services.Proxies.ProfileServiceReference.ModifyProfileResponse retVal = ((Babylon.Services.Proxies.ProfileServiceReference.ProfileService)(this)).ModifyProfile(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Babylon.Services.Proxies.ProfileServiceReference.RemoveAllContactsResponse Babylon.Services.Proxies.ProfileServiceReference.ProfileService.RemoveAllContacts(Babylon.Services.Proxies.ProfileServiceReference.RemoveAllContactsRequest request) {
            return base.Channel.RemoveAllContacts(request);
        }
        
        public void RemoveAllContacts(string id) {
            Babylon.Services.Proxies.ProfileServiceReference.RemoveAllContactsRequest inValue = new Babylon.Services.Proxies.ProfileServiceReference.RemoveAllContactsRequest();
            inValue.Body = new Babylon.Services.Proxies.ProfileServiceReference.RemoveAllContactsRequestBody();
            inValue.Body.id = id;
            Babylon.Services.Proxies.ProfileServiceReference.RemoveAllContactsResponse retVal = ((Babylon.Services.Proxies.ProfileServiceReference.ProfileService)(this)).RemoveAllContacts(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Babylon.Services.Proxies.ProfileServiceReference.RemoveContactResponse Babylon.Services.Proxies.ProfileServiceReference.ProfileService.RemoveContact(Babylon.Services.Proxies.ProfileServiceReference.RemoveContactRequest request) {
            return base.Channel.RemoveContact(request);
        }
        
        public void RemoveContact(string id, string contactID) {
            Babylon.Services.Proxies.ProfileServiceReference.RemoveContactRequest inValue = new Babylon.Services.Proxies.ProfileServiceReference.RemoveContactRequest();
            inValue.Body = new Babylon.Services.Proxies.ProfileServiceReference.RemoveContactRequestBody();
            inValue.Body.id = id;
            inValue.Body.contactID = contactID;
            Babylon.Services.Proxies.ProfileServiceReference.RemoveContactResponse retVal = ((Babylon.Services.Proxies.ProfileServiceReference.ProfileService)(this)).RemoveContact(inValue);
        }
    }
}
