//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Babel.Services.TestClient.ProfileServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profile", Namespace="http://schemas.datacontract.org/2004/07/Babel.Services.Domain")]
    [System.SerializableAttribute()]
    public partial class Profile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Babel.Services.TestClient.ProfileServiceReference.Address AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<Babel.Services.TestClient.ProfileServiceReference.Gender> GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PictureUploadedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UpdatedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Babel.Services.TestClient.ProfileServiceReference.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedOn {
            get {
                return this.CreatedOnField;
            }
            set {
                if ((this.CreatedOnField.Equals(value) != true)) {
                    this.CreatedOnField = value;
                    this.RaisePropertyChanged("CreatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Babel.Services.TestClient.ProfileServiceReference.Gender> Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PictureUploadedOn {
            get {
                return this.PictureUploadedOnField;
            }
            set {
                if ((this.PictureUploadedOnField.Equals(value) != true)) {
                    this.PictureUploadedOnField = value;
                    this.RaisePropertyChanged("PictureUploadedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UpdatedOn {
            get {
                return this.UpdatedOnField;
            }
            set {
                if ((this.UpdatedOnField.Equals(value) != true)) {
                    this.UpdatedOnField = value;
                    this.RaisePropertyChanged("UpdatedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/Babel.Services.Domain")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode {
            get {
                return this.PostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalCodeField, value) != true)) {
                    this.PostalCodeField = value;
                    this.RaisePropertyChanged("PostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gender", Namespace="http://schemas.datacontract.org/2004/07/Babel.Services.Common")]
    public enum Gender : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfileFilter", Namespace="http://schemas.datacontract.org/2004/07/Babel.Services.Filters")]
    [System.SerializableAttribute()]
    public partial class ProfileFilter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeAboveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeBelowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Babel.Services.TestClient.ProfileServiceReference.Gender GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgeAbove {
            get {
                return this.AgeAboveField;
            }
            set {
                if ((this.AgeAboveField.Equals(value) != true)) {
                    this.AgeAboveField = value;
                    this.RaisePropertyChanged("AgeAbove");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgeBelow {
            get {
                return this.AgeBelowField;
            }
            set {
                if ((this.AgeBelowField.Equals(value) != true)) {
                    this.AgeBelowField = value;
                    this.RaisePropertyChanged("AgeBelow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Babel.Services.TestClient.ProfileServiceReference.Gender Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://profile.services.babel.com", ConfigurationName="ProfileServiceReference.IProfileService")]
    public interface IProfileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://profile.services.babel.com/IProfileService/AddProfile", ReplyAction="http://profile.services.babel.com/IProfileService/AddProfileResponse")]
        System.Guid AddProfile(Babel.Services.TestClient.ProfileServiceReference.Profile profile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://profile.services.babel.com/IProfileService/CreateProfile", ReplyAction="http://profile.services.babel.com/IProfileService/CreateProfileResponse")]
        System.Guid CreateProfile(string username, string password, string email, string name, string surname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://profile.services.babel.com/IProfileService/GetProfileByCredentials", ReplyAction="http://profile.services.babel.com/IProfileService/GetProfileByCredentialsResponse" +
            "")]
        Babel.Services.TestClient.ProfileServiceReference.Profile GetProfileByCredentials(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://profile.services.babel.com/IProfileService/GetProfileByID", ReplyAction="http://profile.services.babel.com/IProfileService/GetProfileByIDResponse")]
        Babel.Services.TestClient.ProfileServiceReference.Profile GetProfileByID(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://profile.services.babel.com/IProfileService/GetAllProfiles", ReplyAction="http://profile.services.babel.com/IProfileService/GetAllProfilesResponse")]
        System.Collections.Generic.List<Babel.Services.TestClient.ProfileServiceReference.Profile> GetAllProfiles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://profile.services.babel.com/IProfileService/ModifyProfile", ReplyAction="http://profile.services.babel.com/IProfileService/ModifyProfileResponse")]
        void ModifyProfile(Babel.Services.TestClient.ProfileServiceReference.Profile profile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://profile.services.babel.com/IProfileService/DeleteProfile", ReplyAction="http://profile.services.babel.com/IProfileService/DeleteProfileResponse")]
        void DeleteProfile(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://profile.services.babel.com/IProfileService/SearchProfiles", ReplyAction="http://profile.services.babel.com/IProfileService/SearchProfilesResponse")]
        System.Collections.Generic.List<Babel.Services.TestClient.ProfileServiceReference.Profile> SearchProfiles(Babel.Services.TestClient.ProfileServiceReference.ProfileFilter filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://profile.services.babel.com/IProfileService/AddContact", ReplyAction="http://profile.services.babel.com/IProfileService/AddContactResponse")]
        void AddContact(System.Guid id, System.Guid contactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://profile.services.babel.com/IProfileService/AddContacts", ReplyAction="http://profile.services.babel.com/IProfileService/AddContactsResponse")]
        void AddContacts(System.Guid id, System.Collections.Generic.List<System.Guid> contactIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://profile.services.babel.com/IProfileService/GetContacts", ReplyAction="http://profile.services.babel.com/IProfileService/GetContactsResponse")]
        System.Collections.Generic.List<Babel.Services.TestClient.ProfileServiceReference.Profile> GetContacts(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://profile.services.babel.com/IProfileService/RemoveContact", ReplyAction="http://profile.services.babel.com/IProfileService/RemoveContactResponse")]
        void RemoveContact(System.Guid id, System.Guid contactID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://profile.services.babel.com/IProfileService/RemoveAllContacts", ReplyAction="http://profile.services.babel.com/IProfileService/RemoveAllContactsResponse")]
        void RemoveAllContacts(System.Guid id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfileServiceChannel : Babel.Services.TestClient.ProfileServiceReference.IProfileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfileServiceClient : System.ServiceModel.ClientBase<Babel.Services.TestClient.ProfileServiceReference.IProfileService>, Babel.Services.TestClient.ProfileServiceReference.IProfileService {
        
        public ProfileServiceClient() {
        }
        
        public ProfileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid AddProfile(Babel.Services.TestClient.ProfileServiceReference.Profile profile) {
            return base.Channel.AddProfile(profile);
        }
        
        public System.Guid CreateProfile(string username, string password, string email, string name, string surname) {
            return base.Channel.CreateProfile(username, password, email, name, surname);
        }
        
        public Babel.Services.TestClient.ProfileServiceReference.Profile GetProfileByCredentials(string username, string password) {
            return base.Channel.GetProfileByCredentials(username, password);
        }
        
        public Babel.Services.TestClient.ProfileServiceReference.Profile GetProfileByID(System.Guid id) {
            return base.Channel.GetProfileByID(id);
        }
        
        public System.Collections.Generic.List<Babel.Services.TestClient.ProfileServiceReference.Profile> GetAllProfiles() {
            return base.Channel.GetAllProfiles();
        }
        
        public void ModifyProfile(Babel.Services.TestClient.ProfileServiceReference.Profile profile) {
            base.Channel.ModifyProfile(profile);
        }
        
        public void DeleteProfile(System.Guid id) {
            base.Channel.DeleteProfile(id);
        }
        
        public System.Collections.Generic.List<Babel.Services.TestClient.ProfileServiceReference.Profile> SearchProfiles(Babel.Services.TestClient.ProfileServiceReference.ProfileFilter filter) {
            return base.Channel.SearchProfiles(filter);
        }
        
        public void AddContact(System.Guid id, System.Guid contactID) {
            base.Channel.AddContact(id, contactID);
        }
        
        public void AddContacts(System.Guid id, System.Collections.Generic.List<System.Guid> contactIDs) {
            base.Channel.AddContacts(id, contactIDs);
        }
        
        public System.Collections.Generic.List<Babel.Services.TestClient.ProfileServiceReference.Profile> GetContacts(System.Guid id) {
            return base.Channel.GetContacts(id);
        }
        
        public void RemoveContact(System.Guid id, System.Guid contactID) {
            base.Channel.RemoveContact(id, contactID);
        }
        
        public void RemoveAllContacts(System.Guid id) {
            base.Channel.RemoveAllContacts(id);
        }
    }
}
